export const TEACHER_NAMES = [
  'Dr Bilal Haroon',
  'Mr Raja Anees Taj',
  'Mr Sharafat ali',
  'Mr Anees Taj',
  'MS. Ifrah Arif',
  'Ms Farhat Imtiaz',
  'Dr Aamna Shah',
  'New Appointment',
  'Dr. Iffat Naiyla',
  'Uzma Khanwal',
  'Dr Shoaib Nawaz',
  'Ms Sehrish Arshad',
  'Prof Dr Youns Khan',
  'Mr. Bilal Gumman',
  'Ms. Uzma Nisar',
  'Dr. Yasir Mehmood',
  'Dr. Um e Habiba',
  'Mr. Haisam',
  'Ms. Saima Bibi',
  'Mr. Irfan Aziz',
  'Dr. Sumaira Shamoon',
  'Ms. Nadia Kanwal',
  'Ms. Aliya Azhar',
  'Dr. Nabeela Falaq',
  'Ms. Maria Tariq',
  'Ms. Aisha Jamil',
  'Dr. Ammara Sarwar',
  'Dr. Asif Nawaz',
  'Mr. M. Usman',
  'Ms. Bareera Siraj',
  'Ms. Afshan Shehzadi',
  'Mr. Ali Tariq',
  'Ms. Samina Kausar',
  'Mr. Umar Farooq',
  'Mr. Husnain',
  'Mr. Ikram',
  'Syed Irfan Ali',
  'Ms Sadaf Afreen',
  'Ms Samara Anwar',
  'Dr Wajid Riaz',
  'Mr Asad Qazi',
  'Ms Nazia',
  'Mufti Dilawar Khan',
  'Mr Rana Abdullah',
  'Ms Uzma Kanwal',
  'Ms Summaya Tahir',
  'Dr Safdar',
  'Dr Fareeha',
  'Dr Kanwal Iqbal',
  'Mr Bilal',
  'Dr. Sana Ashraf',
  'Ms. Aasma Iqbal',
  'Miss. Muntaha Saleem',
  'Ms. Fatima Iqbal',
  'Ms. Adeeba',
  'Muhammad Saqib',
  'Mr. Anwar Khan',
  'Mr. Waqas Haider',
  'Ms. Maryam Naseer',
  'Dr. Shoaib Hassan',
  'Mr. Zahid Farooq',
  'Ms. Kiran Shahzadi',
  'Ms. Anam Ahsan',
  'Dr. Waseem Abbasi',
  'Muhammad Imran Hafeez',
  'Muhammad Usman',
  'Ms. Saba Riaz',
  'Ms. Anam Zahoor',
  'Ms. Saira Moin',
  'Dr. Tanzila Kehkashan',
  'Ms. Alishba Farukh',
  'Mr. Yasir Ghayoor',
  'Ms. Neeli Khan',
  'Muhammad Rauf',
  'Mr. Tassawar Abbas',
  'Muhammad Armaghan Tasdageer',
  'Dr. Muhammad Ali',
  'Ms. Shaista Kazim',
  'Mr. Ahmad Sarosh Huda',
  'Ms. Bisma Kazmi',
  'Ms. Ishwa',
  'Dr Azmat Ullah',
  'Mr. Badar e Alam',
  'Mr. Assad Aman Ullah',
  'Dr. Rabia Sattar',
  'Dr. Muhammad Amin',
  'Ms. Tehmeena Ishaq',
  'Ms. Nadia Khan',
  'Miss Sadaf Ghayoor',
  'Ishwa Shoukat',
  'Miss. Samreen',
  'Dr. Fizza Ali Syed',
  'Dr.Quratulain',
  'Dr Sabahat Ali Sheikh',
  'Dr.Anam Saleem',
  'Dr. Rabbia Nasir',
  'Dr. M Soban',
  'Dr. Rabbiyya kauser',
  'Dr. Mulazim Imran',
  'Sir tasawer Abbas',
  'DR.Noor ul Ain',
  'Dr Ahmad',
  'Miss Saman Qadir',
  'New Hiring',
  'Dr. Anum',
  'Dr.Faima Khan',
  'Muhammad Umer',
  'Syeda Hoor Fatima',
  'Mr. Muhammad Adnan Samhi',
  'Dr. Ahmad Hussain',
  'Dr. Manzoor Raza Awan',
  'Dr. Fareeeha Sami',
  'Ms Iqra Jabbar',
  'Ms. Samreen Umar',
  'Ms. Ayesha Rafaqat',
  'Ms. Tehmina Kousar',
  'Mr. Syed Ali Raza',
  'Mr Ahsan Bilal',
  'Miss Samina Mushtaq',
  'Dr M Atif',
  'Mr Hassan Baber',
  'Dr Ali',
  'Ms. Roha Ramash',
  'Dr. Sunbal Khalil',
  'Ms.Hira Fatima',
  'Ms. Aneela',
  'Dr. Safdar Ali',
  'Ms. Aimen Fatima',
  'Mr. M. Ali Shahid',
  'Dr Samina Gull',
  'Ms Ruqia Shabbeer',
  'Ms. Hajra Gul',
  'Dr Hafiz Sajjad Hadir Haidery',
  'Mr. Khubaib',
  'Mr. Noman Sohail',
  'Ms. Aqsa Ejaz',
  'Ms. Ruqaia',
  'Dr. M Waqas',
] as const

export const SUBJECT_NAMES = [
  'Dosage Form Science',
  'Pharmacy Practice-IVA LAB (Dispensing Pharmacy)',
  'Islamic Study',
  'Pharmaceutical Microbiology',
  'Pharmaceutical Math',
  'Pharmacognosy LAB',
  'Pharmacology',
  'Pharmaceutical Organic chemistry',
  'Pharmaceutical Biochemistry',
  'Functional English A',
  'Physiology',
  'Understanding of Holy Quran I',
  'Pharmacology and theraputics IIA',
  'Pharmaceutical Chemistry IIIA (Pharmaceutical Analysis',
  'Pharmacogonsy IIA (Advanced)',
  'Law Taxation and Contract Management',
  'Philosophy, Logic, and Ethics/Introduction to Philosophy',
  'Sustainable Business Strategy/Strategic Management/Strategic Business Management',
  'Planning Control and Performance Management',
  'Introduction to Fintech',
  'Information for management control',
  'Introduction to Business Analytics/Prescriptive Analytics',
  'Opertions Management // Operations Research',
  'Busines Research Methods/Research Method',
  'Principles of Marketing',
  'Functional English',
  'Corporate Law',
  'Islamic Finance',
  'Media Marketing/Digital Marketing',
  'Business Decision Analysis/Business Finance Decision',
  'Translation of Holy Quran IV',
  'Academic English for Business Studies',
  'Translation of Holy Quran/Understanding of Holy Quran',
  'Quantitative Reasoning I',
  'Business Creativity and Innovation',
  'Introduction to Economics/Micro economics',
  'Quantitative Reasoning (II)',
  'Environmental Science',
  'Skill Development Workshops/Life learning skills',
  'Business Finance/ Managing Finance',
  'Entrepreneurship',
  'Applications of Information and Communication Technologies (ICT)/Information Technology',
  'Product and Pricing Strategy',
  'Career Development',
  'Industrial Marketing',
  'Applied Financial Satetment Analysis',
  'Sports',
  'Business taxation (G)',
  'Chinese Language (G)',
  'International Relations',
  'American Literature',
  'Morphology and Syntax',
  'Classical poetry/ Introduction to Poetry',
  'Introduction to Linguistics',
  'Introduction to Literary Studies',
  'Pycholingusitics/Sociolinguitics and Psycholinguistics',
  'Cultural Studies and Ecocriticism',
  'Quantitative Reasoning-11',
  'Literary Criticism-I (from Platonic Idealism to Modernism)',
  'The Postmodern Novel',
  'Translation of Holy Quran-II',
  'Functional English/Critical Reading & Academic Writing/Academic Reading and Writing/English-1',
  'Literary Criticism-11(Contemporary Literary Theory)',
  'Modern Drama',
  'Research Methods in Linguistics',
  'Communication and Presentation Skills',
  'World Englishes',
  'World Literature',
  'Classical Drama',
  'Quantitative Reasoning-I',
  'Foundations of Education',
  'Elementary Mathematics and Statistics',
  'Ideology and Constitution of Pakistan',
  'Evolution (Guided)',
  'Biosafety, Biosecurity and Bioethics',
  'Ecology',
  'Principles of Animal Life-II (Guided)',
  'Wildlife',
  'General Microbiology',
  'Diversity of Invertebrates',
  'Introduction to computer science',
  'Physiology (Guided)',
  'Programming Fundamentals',
  'Mobile Application Development (MADT--4117) - LAB',
  'Artificial Intelligence - LAB',
  'Translation of Holy Quran III',
  'Data Structure and Algorithms - LAB',
  'Computer Organization and Assembly Language - LAB',
  'Software Engineering',
  'Database Systems - LAB',
  'Information Security',
  'Operating Systems',
  'Software Testing & Implmentation',
  'Introduction to Machine Learning',
  'Digital Logic Design',
  'Computer Networks - LAB',
  'Numerical Computing',
  'Object Oriented Programming',
  'Game Application Development',
  'Natural Language Processing',
  'Design and Analysis of Algorithm',
  'Theory of Automata',
  'Database Systems',
  'Software Quality Engineering',
  'Software Metrics',
  'Discrete Structures',
  'Application of Information & Communication Technologies',
  'Web Engineering',
  'Parallel and Distributed Computing',
  'Data Mining/Data Warehousing and Data Mining',
  'Human Resource Management',
  'Visual Programming',
  'Software Re-Engineering',
  'Oganization Behavior & Calture',
  'Applied Physics',
  'Data Strucrues and Algorithms',
  'Software Construction and Development',
  'Human Computer Interaction',
  'Software Requiremnt Engineering',
  'Formal Methods in Software Engineering',
  'Calculus and Analytic Geometry',
  'Translation of Holy Quran II',
  'Ideology and Constitution of Pakistan',
  'Islamic Studies',
  'Management Information Systems',
  'Compiler Construction',
  'Differential Equations',
  'Technical and Business Writing',
  'Pre-Calculus',
  'Numerical Analysis-I',
  'Linear Algebra',
  'Business Process Engineering',
  'Heterocyclic and Organometallic Compounds',
  'Inorganic Chemistry-II',
  'Organic Spectroscopy',
  'Physical Chemistry-II',
  'Introduction to Polymer Chemistry',
  'Organic Chemistry Lab-II',
  'Organic Chemistry-II',
  'Natural Product Chemistry',
  'Radiation and Photochemistry',
  'Inorganic Chemistry',
  'Electrochemistry and Statistical Thermodynamics',
  'Numerical Anaysis II',
  'Methods of Mathematical Physics',
  'Fluid Mechanics-I',
  'Topology',
  'Real Analysis-I/Advanced Math',
  'Technical Writing/Expository writing and Presentation Skills',
  'Graph Theory',
  'Elementary Number Theory',
  'Behavioral Sciences(Psychology & Ethics)',
  'Biostatistic I',
  'Biochemistry II',
  'Physical Agents and Electrotherapy I Lab',
  'English-III(Technical Writing and presentation skills)',
  'Scientific Inquiry and research methodology',
  'Therapeutic Excercises & Techniques',
  'Medicine II',
  'Anatomy',
  'Anatomy-III lab',
  'Anatomy-II',
  'Expository Writing/Communication Skills',
  'Kinesiology-I',
  'Kinesiology-II',
  'Anatomy-IV',
  'Anatomy-IV lab',
  'Physiology',
  'Biochemistry',
  'Medical Physics',
  'Anatomy-I',
  'Pathology & Microbiology I',
  'Supervised Clinical Practice III',
  'Biosafety,patient and Equipment safety',
  'Regional and cross-sectional Imaging Anatomy',
  'Medical Ultrasound Physics and Instrumentation',
  'Medical Imaging in Emergency Medicine',
  'Obstetrtical Ultrasound',
  'Computed Tomography and Imaging Protocols',
  'Musculoskeletal Ultrasound',
  'Introduction to Sustainable Developmental Goals',
  'Metabolic Endocrinology',
  'Food Service Management',
  'Dietetics II',
  'Food Microbiology',
  'Food Processing and Preservation',
  'Micronutrients in Human Nutrition',
  'Physical Education and Sports',
  'Classical Mechanics',
  'Electronics-I',
  'Quantum Mechanics-II',
  'Introduction to Radiation Physics',
  'Environmental Physics',
  'Creative Arts',
  'Nuclear Physics',
  'Mathematical Methods of Physics I',
  'Solid State Physics-I',
  'Modern Physics',
  'Introduction to Material Science',
  'Atomic And Molecular Physics',
  'Introductory Mechanics',
  'Nutritional Chemistry',
  'Education In Pakistan/ Methods of Teaching Urdu in Elementary Schools',
  'Advance Mathematics-IV',
  'School Organization and Management',
  'Teaching of Mathematics/Teaching of Biology/Research Methods in Education',
  'Educational Assessment and Evaluation',
  'Social Foundation of Education: School, Society and Teacher',
  'English-III',
  'Cognitive Psychology',
  'School Psychology',
  'Schools and Perspectives in Psychology',
  'Developmental Psychology',
  'Cross Cultural Psychology',
  'Introduction to Psychology',
  'Research Methods in Psychology',
  'Introduction to Neurobiology',
  'Health Psychology',
  'Personality Theories',
  'Abnormal Psychology',
  'Experimental Psychology',
  'Projective Techniques in Psychology',
  'Child Psychotherapy',
  'Speech and Language Pathology',
  'Science of Happiness',
  'Tools for Quantitaive Reasoning (QR-II)',
  'Nuclear Non-Proliferation Regime',
  'Intro to Sociology',
  'Advance Research Methodology Elements of Social Sciences Research',
  'International Law',
  'Comparative Politics',
  'International Political Economy',
  'Intro to Politics and IR',
  'Peace and Conflict Resolution',
  'Introduction to Governance',
  'Politics and Governance in Pakistan',
  'Determinants of Pakistan\'s Foreign Policy',
  'Introduction to Public Policy',
  'Anthropology',
  'Terrorism, Security and Intelligence',
  'Introduction to Development Studies Policy and Practice',
  'Digitial Transformation and Innovation',
  'Seminar on Emerging Security Threats',
  'Arms Control and Disarmament',
  'Foreign Policy of Major Powers',
  'National Security and Threat Perception',
  'Democracy, Human Rights and Peace Building',
  'Political Theory',
  'Regimes and International Organizations',
  'Introduction to Criminology',
  'Animal Biotechnology',
  'Agricultural Biotechnology',
  'Introduction to Biochemistry',
  'Communication Skills',
  'Industrial Biotechnology',
  'General Microbiology',
  'Cell Biology II',
  'Health Biotechnology',
  'Pakistan studies',
  'Inorganic chemistry',
  'Statistics',
  'Molecular Biology',
  'Research methodology and skill enhancement',
  'Afsanwi Adub ki Asnaf',
  'Iqbal Ki Shairy Ka Fikri Irtqa',
  'Shairy ki Clacki Asnaf',
  'Urdu Adub ki Tahreekain',
  'Urdu Adub ky Ibtdai Adwar',
  'Urdu Noval (Qurqtul Ain sy Bano Qudseya Tak)',
  'Translation of Holy-Quran 11',
  'Tanqeed Aur tazkra Navesi Ka Fan',
  'Urdu Drama (Stage)',
  'Jadeed Urdu Nazam Ka Irtiqa',
  'Fundamentals of Nursing - II',
  'Anatomy & Physiology - II',
  'Applied Nutrition',
  'Theoretical Basis of Nursing',
] as const

export const MAJOR_NAMES = [
  'PHARM-D',
  'LAHORE BUSINESS SCHOOL',
  'ENGLISH',
  'ZOOLOGY',
  'CS & IT',
  'CHEMISTRY',
  'MATHEMATICS',
  'DPT',
  'Radiology and Imaging Technology/Medical Lab Technology',
  'Human Nutrition and Dietetics (BSHND)',
  'PHYSICS',
  'EDUCATION',
  'PSYCHOLOGY',
  'SSISS',
  'BIO TECHNOLOGY',
  'URDU',
  'School of Nursing',
] as const
